name: Run end-to-end tests

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: e2e-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  tsc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '22.13.1'

      - run: |
          npm install

      - name: e2e
        run: |
          npm run e2e
