name: Run unit tests

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '22.13.1'

      - run: |
          npm install

      - name: test
        run: |
          npm run test
